#!/usr/bin/bash
#
#
project="$1"

if [ -z "$project" ]; then
    printf "der skal anføres et mountpoint\n" 
fi

vm=$(hostnamectl | grep Virtualization | awk '{print tolower($2)}')

if [ "$vm" == "oracle" ]; then
    adresse='192.168.10.1'
elif [ "$vm" == "vmware" ]; then
    adresse='172.16.117.1'
else
    printf "Hosten tillader ikke mount fra denne instans"
fi

case "$project" in

    python-demo)
        sudo mount "$adresse":/home/projects/sourcecode/python-demo /nfs/python-demo && cd /nfs/python-demo
        ;;
    bash-demo)
        sudo mount "$adresse":/home/projects/playground/bash-demo /nfs/bash-demo && cd /nfs/bash-demo
        ;;
    *)
        printf "Dette projekt %s kan ikke mountes\n" "$project"
esac

